"""
Django settings for sony project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_URL = "https://sonyapp.bluelogic.ai"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "f!w9%2&_!8*jqg7z5mccgj=k&fj8cxi0j(6y2=wi&7ehsmnsd+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "sonyapp.bluelogic.ai",
    "15.184.106.73",
    "localhost",
    "127.0.0.1",
]

# ALLOWED_HOSTS = "*"


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "api",
    "cms",
    "store_portal",
    "online",
    "api_pos",
    "channels",
]

ASGI_APPLICATION = 'sony.asgi.application'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "sony.middleware.VersionCheckMiddleware",
    "sony.middleware.XApiKeyCheckMiddleware",
    "api.middleware.MdcimAuthenticationMiddleware"
]

ROOT_URLCONF = "sony.urls"
LOGIN_REDIRECT_URL = "home"

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sony.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "sonyapp",
        "USER": "djangouser",
        "PASSWORD": "@djangoUser#1234",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

AUTHENTICATION_BACKENDS = [
    "api.backends.EmailAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Caching

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CACHE_TTL = 60 * 10  # 10 minutes

FIREBASE_CONFIG = {
    "url": "https://fcm.googleapis.com/fcm/send",
    "auth_key": "key=AAAA6Y-l21g:APA91bEUxcAIo1d7J94wgRGSAQt56MPOr6yl_VDSB83eqgKREQRiXAJcSFzPsftX288XRdQRYxQgixckpPRezabQgw4Aps8DqZfTeg20iD-LSF3dlA7PvENqw3DUnC2W1jFyvo_a_tVQ",
    "topic": "/topics/SonyLoyaltyApp",
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dubai"

USE_I18N = True

USE_L10N = True

USE_TZ = True


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.sonyworld.ae"
EMAIL_PORT = 587
EMAIL_HOST_USER = "sonyloyalty@sonyworld.ae"
EMAIL_HOST_PASSWORD = "oAby**s8"
EMAIL_USE_TLS = True


DEFAULT_FROM_EMAIL = "sonyloyalty@sonyworld.ae"


CORS_ORIGIN_ALLOW_ALL = True

LOYALTY_DEFAULT_PERCENTAGE = 5
ONE_LOYALTY_POINT_WORTH_VALUE = 1


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# STATIC_ROOT = os.path.join(BASE_DIR, 'admin_panel/templates')

STATIC_URL = f"{BASE_URL}/django-static/"

STATICFILES_DIRS = (os.path.join(BASE_DIR, "admin_panel/static"),)

MEDIA_URL = f"{BASE_URL}/cms-images/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")


GROWAVE_DETAILS = {
    "get_url": "https://growave.io/api",
    "post_url": "https://api.growave.io/api",
    "client_id": "b0362af38685fc4fb662e892c98abce6",
    "client_secret": "5ff3eb1099fa815c74cdefe0ecd901e5",
}

WEBENGAGE_DETAILS = {
    "license_code": "76aaaa0",
    "api_key": "26e1b648-70d1-4246-b184-8e8730d0b951",
    "url": "https://api.webengage.com/v1/accounts",
}

SSO_URL = "https://api.acm.account.sony.com"
MDCIM_CLIENT_ID = "b1968727-46c5-415f-9b69-8131ae26e6b5"
MDCIM_CLIENT_SECRET = "ce86336b-5093-4ff9-9a2b-5c24d13e85b4"
MDCIM_API_KEY = "YjE5Njg3MjctNDZjNS00MTVmLTliNjktODEzMWFlMjZlNmI1OjcwOTBiNjViLWM5ZDctNDU2NS05MzliLWQ1ZmU5MzhkYThjZQ=="
MDCIM_REDIRECT_URL = "https://sonyapp.bluelogic.ai/v2/app/sso-login"
